### ISSUE TITLE
Default Hyde mobile theming

### ISSUE THREAD

**Issue by juszczakn** [kingcons/coleslaw#104]
The default Hyde theme looks fine IMO, however it is not responsive at all to mobile devices. It would be great if the default theme laid the site out better on mobile. 

I'm going to be updating it for mobile myself, will send a PR if wanted.

**Comment by PuercoPop** [comment]
Better mobile support by the default theme, hyde, is certainly welcome. When you send the PR, if you can, attach screenshots of how a site looks before and after the changes

**Comment by kingcons** [comment]
Thanks @juszczakn!
