### ISSUE TITLE
Package COLESLAW-CONF does not exist.

### ISSUE THREAD

**Issue by ebrasca** [kingcons/coleslaw#110]
CL-USER> (ql:quickload :coleslaw)
To load "coleslaw":
  Load 1 ASDF system:
    coleslaw
; Loading "coleslaw"
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Package COLESLAW-CONF does not exist.
;   
;       Line: 72, Column: 42, File-Position: 2833
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/ebrasca/src/lisp/coleslaw/src/util.lisp" {1006128A73}>
; 
; compilation unit aborted
;   caught 3 fatal ERROR conditions
;   caught 1 ERROR condition

**Comment by PuercoPop** [comment]
Thanks for reporting this! I can reproduce in CCL and SBCL.

The package is being defined in the ASDF file, which in theory shouldn't run code. It appears that an ASDF is not evaluating the code at the end of the file nowadays, so the package is not being created.

One way to solve this would be to move *base-dir* to the god object, BLOG. Another solution would be to move the package creation to a `:before load-op` method. Was the idea of the coleslaw-conf package to slowly move things from the god object? What solution do you prefer @kingcons?

**Comment by dkochmanski** [comment]
why do you want to define packages in `asd` file btw? Is there any reason to bundle build system with the software so tightly?
