### ISSUE TITLE
Documentation inconsistency: Date metadata is required

### ISSUE THREAD

**Issue by PuercoPop** [kingcons/coleslaw#121]
The [readme](https://github.com/kingcons/coleslaw/blob/master/README.md) states that `Posts require the title: and format: fields.`. However Posts require dates as well, otherwise the call [ALL-MONTHS](https://github.com/kingcons/coleslaw/blob/master/src/indexes.lisp#L95) signals an error as `(subseq nil 0 7)` is out of bounds.

Should we modify the readme or modify the code so that it doesn't require the date? Another option would be for the date could be filled with the creating-time of the file which shouldn't be much code.

**Comment by Ferada** [comment]
Where would posts without dates be linked from, just via the tags / title?

I'd probably go with retrieving the creation date, assuming that's properly stored in Git (it is, isn't it?)

**Comment by PuercoPop** [comment]
I assume so though I haven't checked, using sb-posix and ccl's equivalent would be another easy way.

**Comment by PuercoPop** [comment]
SBCL is easy but CCL doesn't seem to include a posix contrib :'(. We could use inferior-shell to extract the creation time as it is already a dependency?

**Comment by Ferada** [comment]
Isn't that just [`FILE-WRITE-DATE`](http://clhs.lisp.se/Body/f_file_w.htm)? Then we just need a conversion to normal timestamps or something and it should be portable as well.

**Comment by PuercoPop** [comment]
Nice, I didn't know about `FILE-WRITE-DATE`. However It appears that [git doesn't preserves mtime](http://stackoverflow.com/questions/21735435/git-clone-changes-file-modification-time) [[2]](http://kerneltrap.org/mailarchive/git/2007/3/1/240167), in retrospect it seems sensible. So it doesn't seem we can use the file time stamps.

It appears the only options are to either update the documentation or #122 (the templates already don't assume there is date) :sob:

**Comment by Ferada** [comment]
Too bad; so what's the use case for not having a date? I'd rather make the code simpler and always have it, that'd be more straightforward - if you think #122 is good enough it looks fine to me too though.

**Comment by kingcons** [comment]
Hmm. Yeah, I think I prefer #122 to assuming that all content we get is dated. And the documentation is correct IMO, we shouldn't force users to date their posts but if they don't we can't provide Date indexes for that content. :+1: Thanks, y'all. <3 :100:
