### ISSUE TITLE
Feature request: Posts have their own pages

### ISSUE THREAD

**Issue by z3t0** [kingcons/coleslaw#139]
I have started porting over a jekyll blog to coleslaw. The first main issue I came up against was that my entire post was being shown on the index page, when ideally only a preview should be there. Clearly this is a preference of mine and it's fine if it is not the norm. But having this functionality may be useful to others as well.

Can you point me in the right direction so that I can implement this feature myself, eg. is this a feature of the theme or the generator itself.

**Comment by PuercoPop** [comment]
Just to be clear, posts have their own page/url. What you seem to be looking is for is the excerpt functionality implemented in https://github.com/kingcons/coleslaw/pull/129

**Comment by z3t0** [comment]
Thanks I'll follow there.
