### ISSUE TITLE
[Question] Is putting something in $HOME necessary??

### ISSUE THREAD

**Issue by guicho271828** [kingcons/coleslaw#143]
I consider start using it, but was kind of deflected at the second step which says I have to put something in a home directory.

I want every blog-related files in a single repository (except quicklisp), just like what Jekyll does. I do not want to contaminate $HOME. Can I skip this step?

**Comment by guicho271828** [comment]
I just submited the PR to README.

**Comment by PuercoPop** [comment]
Oi @guicho271828, sorry for the late reply. IIRC we look for the RCfile first in the blog directory (or CWD) so it is not necessary for the config file to be in your $HOME dir.

We'll look into your PRs tomorrow

**Comment by guicho271828** [comment]
thanks, Im now learning how coleslaw works and trying to improve the usability.
