### ISSUE TITLE
The basic functionality doesn't work due to an obvious bug? Am I missing something?

### ISSUE THREAD

**Issue by guicho271828** [kingcons/coleslaw#145]
This line https://github.com/kingcons/coleslaw/blob/master/src/content.lisp#L68 parses the metadata and the result is obviously a string. Thus `format: md` reads as `:format "md"`.

The results are sent back to [read-content](https://github.com/kingcons/coleslaw/blob/master/src/content.lisp#L80) and [discover](https://github.com/kingcons/coleslaw/blob/master/src/content.lisp#L80) and then a POST instance is instantiated with these metadata through [construct](https://github.com/kingcons/coleslaw/blob/master/src/util.lisp#L23) which is just a wrapper of `make-instance`. During instantiation [render-text](https://github.com/kingcons/coleslaw/blob/master/src/posts.lisp#L12) is called with the `format` slot of the POST instance, which has the value `"md"` mentioned earlier. But `render-text` is eql-specialized with a keyword `:md`, so it signals a no-applicable-method error.

**Comment by guicho271828** [comment]
#146 fixes this.

**Comment by PuercoPop** [comment]
Thanks for tracking this down. It was a careless change on my part.
