### ISSUE TITLE
Feature wish: Add a search function (this is a race ;-))

### ISSUE THREAD

**Issue by dertuxmalwieder** [kingcons/coleslaw#95]
Hi,

(sorry, this one will be longish, but I want to make my points clear…,)

having been in the process of transitioning from WordPress to some static (not just flat-file) blog for years now (I’m *really* lazy), I still haven’t settled to which system to use. Actually, I had found one which I thought would be perfect, then I noticed that the provided solution for searching articles was not working as intended, especially since there was no way to use it without JavaScript. The most important feature of a blog system **is** a good search functionality, followed by a decent comment solution (but that’s a different thing).

So I’m back on track, looking for *the perfect* static blog solution. I already have a list of such systems which failed to work well for me (mostly theming- or feature-related issues), so I loosened my requirements a bit. I don’t even care which programming language is used anymore as long as it *just works* (as in *it provides a good search function*) and it’s a cool one (as in *it’s not JavaScript*).

**Now here’s what I want:**

The *perfect* static blog solution should, while generating the pages, keep some *full-text index* of the posts and provide a search function which could be accessed through the front-end (like the article listing but filtered by contents). In case this is already possible, please tell me how - I actually searched the docs *and* sources but I haven’t found such a functionality.

As I want you to actually consider this - I know - frequent feature wish within the near future, I posted it to several interesting generators’ issue trackers, including yours. I’ll probably use the Static Site Generator which comes up with a sufficient search functionality first.

Thank you in advance.

**Comment by lukasepple** [comment]
Coleslaw has now means of efficiently implementing a search engine algorithm since it generates *static* files. It would be possible to generate a Index and have a huge JS file loaded by the browser. This would use up the browser's computing power, be bloaty and annoying to implement.

You could either add a search form using google with the`site:` restriction or use a dynamic, flat-file based blog engine.

**Comment by dertuxmalwieder** [comment]
Why would the index have to be client-side? As far as I understand the system, it would be enough to have a server-side index and a Lisp script to search in it.

**Comment by lukasepple** [comment]
There is no such thing as a server doing anything in coleslaw's design. There's only a dumb http server, serving .html files.

**Comment by lukasepple** [comment]
I think you misunderstand what a static site generator is. It is a software that runs on your local machine and generates .html files from templates and posts/sites that are meant to be uploaded to a server.
